
--CREATE DATABASE SUPERMERCADO


--SE CREA UNA TABLA "GRUPOS"

CREATE TABLE GRUPOS(
	COD_GRUPO INT NOT NULL,
	NOMBRE_GRUPO VARCHAR(50) NULL,
	PRIMARY KEY (COD_GRUPO)
);


--POBLAR LA TABLA

INSERT INTO GRUPOS (COD_GRUPO, NOMBRE_GRUPO)
VALUES (1, 'Frutas');
INSERT INTO GRUPOS (COD_GRUPO, NOMBRE_GRUPO)
VALUES (2, 'Verduras');
INSERT INTO GRUPOS (COD_GRUPO, NOMBRE_GRUPO)
VALUES (3, 'Hortalizas');


--MOSTRAR DATOS
SELECT *
FROM GRUPOS

--ELIMINAR UN DATO
--DELETE FROM GRUPOS WHERE COD_GRUPO = 5

--DELETE FROM GRUPOS


-----------------------------------------PRODUCTOS

CREATE TABLE PRODUCTOS(
	COD_PRODUCTO INT NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(100) NULL,
	COD_GRUPO INT NOT NULL,
	PRECIO FLOAT NOT NULL,
	PRIMARY KEY (COD_PRODUCTO),
	FOREIGN KEY (COD_GRUPO) REFERENCES GRUPOS (COD_GRUPO)
);

INSERT INTO PRODUCTOS (COD_PRODUCTO, NOMBRE_PRODUCTO,
COD_GRUPO, PRECIO) VALUES (1, 'Mandarina', 1, 3.93);
INSERT INTO PRODUCTOS (COD_PRODUCTO, NOMBRE_PRODUCTO,
COD_GRUPO, PRECIO) VALUES (2, 'Lechugas', 2, 1.63);
INSERT INTO PRODUCTOS (COD_PRODUCTO, NOMBRE_PRODUCTO,
COD_GRUPO, PRECIO) VALUES (3, 'Melones', 1, 1.94);
INSERT INTO PRODUCTOS (COD_PRODUCTO, NOMBRE_PRODUCTO,
COD_GRUPO, PRECIO) VALUES (4, 'Coles', 2, 0.61);

--MOSTRAR TODOS LOS PRODUCTOS
SELECT *
FROM PRODUCTOS



----CONSULTAS
--1) Mostrar los datos del grupo FRUTAS
select * from GRUPOS where NOMBRE_GRUPO = 'Frutas'
select * from GRUPOS where COD_GRUPO = 1

--2) Mostrar los productos que pertenecen al grupo FRUTAS
select P.*
from GRUPOS G, PRODUCTOS P
WHERE G.COD_GRUPO = P.COD_GRUPO
AND G.NOMBRE_GRUPO = 'Frutas'

--3) Mostrar los productos con precio > 1
select *
from PRODUCTOS 
where PRECIO > 1


